apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvweb
    labels:
         app: myweb
spec:
    accessModes:
     -  ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: web-svc
spec:
  selector:
    app: myweb
  type: NodePort
  ports:
    - nodePort: 31180
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpdeploy
    labels:
         app: myweb
spec:
    replicas: 3
    selector:
         matchLabels:
             app: myweb
             env: production
    template:
         metadata:
              name: phppod
              labels:   
                  env: production
                  app: myweb
         spec:
              containers:
              -   name: phpcon
                  image: vimal13/apache-webserver-php
                  ports:
                  -    containerPort: 80
                  volumeMounts:
                  -    mountPath: "/var/www/html"
                       name: mypvc
              volumes:
              -   name: mypvc
                  persistentVolumeClaim:
                       claimName: pv-webapp
